import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("audit page leads with three AI-controlled depths and keeps tools as advanced boundaries", async () => {
  const html = await readFile(new URL("../src/web/index.html", import.meta.url), "utf8");
  const app = await readFile(new URL("../src/web/app.js", import.meta.url), "utf8");
  const copilotControls = await readFile(new URL("../src/web/copilot-controls.js", import.meta.url), "utf8");
  const copilotOptions = await readFile(new URL("../src/web/copilot-options.js", import.meta.url), "utf8");
  const auditInputControls = await readFile(new URL("../src/web/audit-input-controls.js", import.meta.url), "utf8");
  const server = await readFile(new URL("../src/server/index.js", import.meta.url), "utf8");
  for (const id of ["depth-review", "depth-targeted", "depth-full", "allow-local-execution", "allow-anvil", "allow-forks", "test-campaign-mode", "generated-test-budget", "fuzz-runs", "invariant-runs", "invariant-depth", "campaign-timeout"]) {
    assert.match(html, new RegExp(`id="${id}"`));
  }
  assert.doesNotMatch(html, /up to three generated/i);
  assert.match(html, /max="50"/);
  assert.match(html, /max="100000"/);
  assert.match(app, /auditDepth: selectedAuditDepth\(\)/);
  assert.match(app, /allowLocalExecution: elements\["allow-local-execution"\]\.checked/);
  assert.match(app, /allowAnvil: elements\["allow-anvil"\]\.checked/);
  assert.match(app, /allowForks: elements\["allow-forks"\]\.checked/);
  assert.equal((html.match(/name="audit-depth"/g) || []).length, 3);
  assert.match(app, /elements\["depth-targeted"\]\.checked = true/);
  assert.match(html, /Whole-contract logic tracing, source-cited findings, and limits/);
  assert.match(html, /AI runs only the checks needed to answer material questions/);
  assert.match(html, /AI attempts every applicable installed evidence class/);
  assert.match(html, /Advanced tool boundaries/);
  assert.match(html, /These are boundaries, not extra audit modes/);
  assert.match(html, /id="cancel-audit"/);
  assert.match(app, /\/api\/audits\/\$\{activeJob\.id\}\/cancel/);
  assert.match(app, /testCampaign:/);
  assert.match(html, /Post-MVP remediation services/);
  assert.match(html, /Only read-only auditing is available in this MVP/);
  assert.match(html, /Propose repairs/);
  assert.match(html, /Repair workspace/);
  assert.equal((html.match(/disabled>Outside MVP/g) || []).length, 2);
  assert.match(html, /id="source-highlight"[^>]*aria-hidden="true"/);
  assert.match(html, /id="source-editor"[^>]*wrap="off"/);
  assert.match(html, /id="source-editor"[^>]*placeholder="\/\/ Example only/);
  assert.match(html, /id="load-file"[^>]*type="button"/);
  assert.match(html, /id="new-audit"[^>]*type="button">Start new audit/);
  assert.match(html, /id="file-input"[^>]*type="file"/);
  assert.match(app, /import \{ highlightSolidity \} from "\/solidity-highlight\.js"/);
  assert.match(app, /source: elements\["source-editor"\]\.value/);
  assert.doesNotMatch(app, /const sample/);
  assert.match(app, /let fileName = "Target\.sol"/);
  assert.match(app, /if \(!elements\["source-editor"\]\.value\.trim\(\)\)/);
  assert.match(app, /Load a \.sol file or paste Solidity source before starting an audit/);
  assert.match(app, /size > 300_000/);
  assert.match(app, /event\.target\.value = ""/);
  assert.match(app, /elements\["file-input"\]\.click\(\)/);
  assert.match(app, /elements\["new-audit"\]\.addEventListener\("click", startNewAudit\)/);
  assert.match(app, /function startNewAudit\(\)/);
  assert.match(app, /function startNewAudit\(\)[\s\S]*detachActiveJob\(\);[\s\S]*fileName = "Target\.sol"/);
  assert.match(app, /function startNewAudit\(\)[\s\S]*elements\["source-editor"\]\.value = ""/);
  assert.match(app, /function startNewAudit\(\)[\s\S]*syncSourceEditor\(\)/);
  assert.match(app, /New audit ready\. Load a \.sol file or paste Solidity source/);
  assert.match(app, /localStorage\.removeItem\(ACTIVE_JOB_STORAGE_KEY\)/);
  assert.match(app, /elements\["new-audit"\]\.classList\.toggle\("hidden", !job \|\| controls\.loadDisabled\)/);
  assert.match(app, /Loaded \$\{file\.name\} as a read-only audit copy/);
  assert.match(app, /The previous audit remains saved locally/);
  assert.match(app, /deriveAuditInputControls\(job\)/);
  assert.match(auditInputControls, /loadDisabled: operationActive/);
  assert.match(app, /import \{ deriveAuditInputControls \} from "\/audit-input-controls\.js"/);
  assert.match(server, /"\/audit-input-controls\.js": \["audit-input-controls\.js"/);
  assert.match(server, /"\/copilot-options\.js": \["copilot-options\.js"/);
  assert.match(app, /new FileReader\(\)/);
  assert.match(html, /Audit findings and readiness/);
  for (const id of ["audit-progress", "audit-progress-title", "audit-progress-count", "audit-progress-track", "audit-progress-bar", "audit-progress-detail", "audit-progress-spinner"]) {
    assert.doesNotMatch(html, new RegExp(`id="${id}"`));
  }
  assert.doesNotMatch(html, /id="practical-report"/);
  assert.doesNotMatch(html, /role="progressbar"/);
  assert.doesNotMatch(app, /renderAuditProgress\(job\)/);
  assert.doesNotMatch(app, /renderPracticalReport\(job\)/);
  assert.match(app, /deriveAuditProgress, pollAuditJob \} from "\/audit-progress\.js"/);
  assert.match(app, /const progress = deriveAuditProgress\(job\)/);
  assert.match(app, /renderLiveAuditStatus\(job\)/);
  assert.match(app, /const entries = \[\.\.\.activity,[\s\S]*\.sort/);
  assert.doesNotMatch(app, /children\.push\(renderCopilotEntry\(progressEntry\)\)/);
  assert.match(app, /kind: event\.status === "running" \? "activity" : event\.status/);
  assert.match(app, /event\.stage === "operation-loop"/);
  for (const label of ["Slither", "Aderyn", "Anvil local chain", "Foundry testing", "Compiler matrix"]) assert.match(app, new RegExp(label));
  assert.match(app, /buildPracticalConclusionEntries\(job\)/);
  for (const id of ["copilot-status", "copilot-feed", "copilot-live-status", "copilot-live-spinner", "copilot-live-title", "copilot-live-detail", "copilot-live-count", "copilot-input", "copilot-send", "copilot-help", "copilot-error"]) {
    assert.match(html, new RegExp(`id="${id}"`));
  }
  assert.match(app, /elements\["copilot-live-spinner"\]\.classList\.toggle\("hidden", !progress\.active\)/);
  assert.doesNotMatch(app, /entry\.kind === "running"[\s\S]*activity-spinner/);
  assert.doesNotMatch(html, /id="copilot-confirm"/);
  assert.match(html, /Audit Copilot/);
  assert.match(html, /one interpreted audit stream/i);
  assert.match(html, /additional AI turn/i);
  assert.doesNotMatch(html, /pipeline-panel/);
  assert.doesNotMatch(html, /copilot-inspectors/);
  assert.doesNotMatch(html, /id="worklog"/);
  assert.doesNotMatch(html, /id="copilot-evidence"/);
  assert.doesNotMatch(html, /id="summary-strip"/);
  assert.doesNotMatch(html, /class="suite-panel"/);
  assert.doesNotMatch(html, /id="findings"/);
  assert.equal((html.match(/role="log"/g) || []).length, 1);
  assert.match(app, /renderCopilot\(job\)/);
  assert.match(app, /buildEvidenceEntries\(job\)/);
  assert.match(app, /buildVerificationEntries\(job\)/);
  assert.match(app, /Coverage summary/);
  assert.match(app, /verification-coverage-gaps/);
  assert.match(app, /const answered = job\.verificationResults\.filter/);
  assert.match(app, /const gaps = job\.verificationResults\.filter/);
  assert.doesNotMatch(app, /Targeted next check/);
  assert.match(app, /AI-evidence-supported/);
  assert.match(app, /auditEventDetails\(job, event\)/);
  assert.match(app, /copilot-message-details/);
  assert.match(app, /Analyzer evidence/);
  assert.match(app, /Property outcome/);
  assert.match(app, /rejected before Forge/);
  assert.doesNotMatch(app, /confirmAiUsage|copilot-confirm/);
  assert.match(app, /import \{ deriveCopilotControls \} from "\/copilot-controls\.js"/);
  assert.match(app, /deriveCopilotControls\(\{ job: activeJob, authConnected: auth\.connected, jobUnavailable: activeJobUnavailable \}\)/);
  assert.doesNotMatch(app, /copilot-input.*value\.trim\(\).*disabled/);
  assert.match(copilotControls, /Send this question as a new AI turn/);
  assert.match(app, /The local service restarted and this audit is no longer active/);
  assert.match(app, /\/api\/audits\/\$\{jobId\}\/copilot/);
  assert.match(app, /Questions start a separate AI turn/);
  assert.match(html, /id="fork-network"/);
  assert.match(html, /Ethereum Mainnet/);
  assert.match(html, /Base Mainnet/);
  assert.match(html, /BNB Smart Chain/);
  assert.match(app, /data-followup-action/);
  assert.match(app, /Continue testing/);
  assert.doesNotMatch(app, /Run this property check/);
  assert.doesNotMatch(html, /id="copilot-options"/);
  assert.match(app, /const actionMessage = renderCopilotOptions\(job\)/);
  assert.match(app, /children\.push\(actionMessage\)/);
  assert.match(app, /copilot-feed"\]\.addEventListener\("click", handleCopilotOptionAction\)/);
  assert.match(copilotOptions, /AI chooses and runs the next campaign/);
  assert.match(copilotOptions, /Information needed/);
  assert.match(copilotOptions, /Finish report/);
  assert.doesNotMatch(copilotOptions, /questionOption/);
  assert.match(app, /\/followups/);
  assert.doesNotMatch(app, /respond\.disabled = !controls\.ready/);
  assert.match(app, /respond\.dataset\.copilotFocus = "true"/);
  assert.match(app, /copilot-option-detail/);
  assert.doesNotMatch(app, /promptButton\.dataset\.copilotPrompt/);
  assert.match(app, /copilot-suggestion-note/);
  assert.doesNotMatch(app, /suggestion\.dataset\.copilotPrompt = step\.label/);
  assert.doesNotMatch(app, /copilot-suggestion-action/);
  assert.doesNotMatch(app, /input\.value = input\.value\.trim\(\).*copilotPrompt/s);
  assert.match(app, /if \(!questionOverride\) elements\["copilot-input"\]\.value = ""/);
  assert.match(app, /job\.reportState\.retryable === true/);
  assert.match(app, /\/api\/audits\/\$\{jobId\}\/finalize/);
  assert.match(app, /job\.reportState\?\.status !== "ready"/);
  assert.match(app, /elements\["source-editor"\]\.readOnly = controls\.sourceReadOnly/);
  assert.match(app, /Load another \.sol file to start a separate audit/);
  assert.match(html, /Press Enter to send or Shift\+Enter for a new line/);
  assert.match(app, /addEventListener\("keydown", submitCopilotOnEnter\)/);
  assert.match(app, /event\.key !== "Enter" \|\| event\.shiftKey \|\| event\.isComposing/);
  assert.match(app, /if \(!elements\["copilot-send"\]\.disabled\) askCopilot\(\)/);
  assert.match(app, /wasNearBottom/);
  assert.match(app, /expandedCopilotEntries/);
  assert.match(app, /details\.copilot-message\[data-entry-id\]/);
  assert.match(app, /item\.open = expandedCopilotEntries\.has\(entry\.id\)/);
  assert.doesNotMatch(html, /judge-facing/i);
  assert.match(html, /The AI auditor decides whether testing is useful/);
  assert.doesNotMatch(html, /Quick triage|fixed 3 harness ceiling/);
  assert.doesNotMatch(app, /preventDefault\(\).*setRangeText/s);
  assert.match(app, /localStorage\.getItem\(ACTIVE_JOB_STORAGE_KEY\)/);
  assert.match(app, /pollAuditJob/);
  assert.match(app, /data-cancel-followup/);
  assert.doesNotMatch(app, /renderPracticalReport\(job\)/);
  assert.doesNotMatch(app, /renderSummary\(|renderSuite\(|renderFindings\(|renderTouchpointPanel\(|renderWorklog\(/);
  for (const id of ["practical-report", "practical-verdict", "practical-findings", "practical-gaps"]) assert.doesNotMatch(html, new RegExp(`id="${id}"`));
});
